# Generated by Django 5.0 on 2025-02-19 18:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("painel", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientessinais",
            options={
                "managed": False,
                "verbose_name": "Receptor de Sinal",
                "verbose_name_plural": "Receptores de Sinais",
            },
        ),
        migrations.AlterModelOptions(
            name="sinaisrecebidos",
            options={
                "managed": False,
                "verbose_name": "Emissor de Sinal",
                "verbose_name_plural": "Emissor de Sinais",
            },
        ),
    ]
