# Generated by Django 5.0 on 2025-02-20 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("painel", "0002_alter_clientessinais_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientessinais",
            options={
                "managed": False,
                "verbose_name": "2- Receptor de Sinal",
                "verbose_name_plural": "2 - Receptores de Sinais",
            },
        ),
        migrations.AlterModelOptions(
            name="metatraderhistorico",
            options={
                "managed": False,
                "verbose_name": "3- Historico de Operações",
                "verbose_name_plural": "3 - Historico de Operações",
            },
        ),
        migrations.AlterModelOptions(
            name="sinaisrecebidos",
            options={
                "managed": False,
                "verbose_name": "1 - Emissor de Sinal",
                "verbose_name_plural": "1 - Emissor de Sinais",
            },
        ),
    ]
