# Generated by Django 5.0 on 2025-02-20 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientessinais",
            options={
                "managed": False,
                "verbose_name": "Receptor de Sinal",
                "verbose_name_plural": "Receptores de Sinais",
            },
        ),
    ]
