# Generated by Django 5.0 on 2025-02-20 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_clientessinais_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientes",
            options={
                "managed": False,
                "verbose_name": "1 - Cadastro Cliente",
                "verbose_name_plural": "1 - Cadastro Clientes",
            },
        ),
        migrations.AlterModelOptions(
            name="clientessinais",
            options={
                "managed": False,
                "verbose_name": "3 - Cadastro de Receptor",
                "verbose_name_plural": "3 - Cadastro de Receptores",
            },
        ),
        migrations.AlterModelOptions(
            name="metatraderhistorico",
            options={
                "managed": False,
                "verbose_name": "4 - Historico de Operações",
                "verbose_name_plural": "4 - Historico de Operações",
            },
        ),
        migrations.AlterModelOptions(
            name="sinaisrecebidos",
            options={
                "managed": False,
                "verbose_name": "2 - Cadastro de Emissor",
                "verbose_name_plural": "2 - Cadastro de Emissores",
            },
        ),
    ]
